server:
  port: 8001

# mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml #定义mybatis配置文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml      #定义扫描mapper位置的属性
  type-aliases-package: ahead.pojo  # 指定POJO扫描包来让mybatis自动扫描到自定义POJO （springcloud-api模块中的Javabean位置）


# spring配置
spring:
  application:
    name: springcloud-provider-dept  #微服务项目起到唯一标识的作用，（让注册中心知道你注册的这个服务实例，逻辑上是属于哪个服务的）
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

# Eureka 配置：配置服务注册中心地址
eureka:
  client:
    service-url: # 配置服务注册中心地址；http://localhost/7001 是springcloud-eureka-7001模块的访问地址
      #defaultZone: http://localhost:7001/eureka/
      # 将当前provider-8001实例，注册到三个注册中心地址（7001-7003）
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8001 #修改Eureka上的默认描述信息status

#  关闭自我保护机制，不可用的微服务会被及时踢除
#eureka.server.enable-self-preservation: false


# info配置
info:
  company.name: com.ahead

# 解决author/info页面404无法打开问题
management:
  endpoints:
    web:
      exposure:
        include: "*"
